### ISSUE TITLE
Video format error

### ISSUE THREAD

**Issue by PlkMarudny** [meigo/svelte-video-player#5]
I have noticed url are checked for the extensions, and if the extension is not present, cosole.error() is invoked. Some video's url have no extension however, but the player plays them just fine. Maybe it would be beneficial to get rid of this console noise?

if you check this [link](https://media.gettyimages.com/videos/typhoon-at-philippines-woman-wearing-raincoat-walking-at-rural-road-video-id959629488?b=1&k=6&m=959629488&h=q4ayn8qrJV70tIJhmJqK5CfBe5132tPSeHH6VHBWCfQ=) for example; the video plays just fine.

**Comment by meigo** [comment]
Makes sense, thanks. Fixed that.
